### ISSUE TITLE
Cannot exclude files from coverage report

### ISSUE THREAD

**Issue by antebudimir** [cenfun/vitest-monocart-coverage#1]
Hi, CenFun!

So, I've been trying to set up Monocart coverage in my Next.js 13.5.6 app with Vitest 1.6.0 and Playwright 1.44.1. While I've sorted Playwright without any issues whatsoever, I've been struggling with Vitest for a week already. 

This is my Vitest config:
```
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react(), vanillaExtractPlugin()],
  test: {
    coverage: {
      enabled: true,
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.test.ts?(x)',
        'src/**/*.css.ts',
        'src/**/*.ts.vanilla.css',
        './vitest.setup.mts',
      ],
      provider: 'custom',
      customProviderModule: 'vitest-monocart-coverage',
      coverageReportOptions: {
        logging: 'debug',
        name: 'School Portal Vitest Coverage Report',
        reports: ['console-details', 'v8'],
        lcov: true,
        outputDir: './coverage/vitest-reports',
        include: ['src/**/*.ts'],
        exclude: [
          'src/**/*.test.ts?(x)',
          'src/**/*.css.ts',
          'src/**/*.ts.vanilla.css',
          './vitest.setup.mts',
        ],
      },
      reporter: ['html', 'text', 'json'],
      reportsDirectory: './coverage/vitest-reports',
    },
    reporters: [
      ['html', { outputFile: './coverage/vitest-reports/vitest-report.html' }],
      ['json', { outputFile: './coverage/vitest-reports/vitest-report.json' }],
      ['junit', { outputFile: './coverage/vitest-reports/vitest-report.xml' }],
    ],
    environment: 'jsdom',
    globals: true,
    include: ['src/**/*.test.ts?(x)'],
    mockReset: true,
    setupFiles: ['./vitest.setup.mts'],
  },
});
```

And I'm constantly getting this report:
![2024-06-17 16 07 35](https://github.com/cenfun/vitest-monocart-coverage/assets/57053530/00435c68-9c7c-48f2-ad88-7e74ea8077af)

Is there a config option that I'm missing?

Also, I'm getting this error:
_Object literal may only specify known properties, and 'coverageReportOptions' does not exist in type '{ provider: "custom"; } & CustomProviderOptions'.ts(2769)
reporters-yx5ZTtEV.d.ts(1993, 18): The last overload is declared here._

**Comment by cenfun** [comment]
> Object literal may only specify known properties, and 'coverageReportOptions' does not exist in type '{ provider: "custom"; } & CustomProviderOptions'.ts(2769)

NOTE: the `coverageReportOptions` is unknown property of Vitest `coverage` when using Typescript. Please move the `coverageReportOptions` to default config file `mcr.config.js`

> Cannot exclude files from coverage report

I don't think `MCR` can support `include` or `exclude`, please use right options like `entryFilter` or `sourceFilter`. see [here](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#filtering-results)
