### ISSUE TITLE
Setting coverageReportOptions in config when using Typescript

### ISSUE THREAD

**Issue by jensborje** [cenfun/vitest-monocart-coverage#2]
In the `README.md`, it says

>NOTE: coverageReportOptions is unknown property of Vitest coverage when using Typescript. Please move the coverageReportOptions to default config file `mcr.config.js`

How is this achieved? Adding the following to the mentioned file makes no difference.

```
// mcr.config.js
const coverageReportOptions = {
    logging: 'debug',

    name: 'My Vitest Unit Coverage Report',
 
    outputDir: 'coverage-reports/unit',
    reports: [
        'console-details',
        'v8',
        'raw'
    ],
};

export default coverageReportOptions;
```

Running `vitest run --coverage` does produce a coverage report in terminal, mentioning monocart. However, there is no report produced in the `outputDir`. This draws me to the assumption that the config file isn't picked up.

**Comment by cenfun** [comment]
Pelase try vitest-monocart-coverage@2.1.0
In fact, I don't know why have this issue, but I have optimized the loading of the config file, which should be able to support more default config files
- mcr.config.js
- mcr.config.cjs
- mcr.config.mjs
- mcr.config.json
- mcr.config.ts

**Comment by jensborje** [comment]
> Pelase try vitest-monocart-coverage@2.1.0 In fact, I don't know why have this issue, but I have optimized the loading of the config file, which should be able to support more default config files
> 
> * mcr.config.js
> * mcr.config.cjs
> * mcr.config.mjs
> * mcr.config.json
> * mcr.config.ts

Thank you! This works after upgrading to `2.1.0`.
