### ISSUE TITLE
Coverage report not generated 

### ISSUE THREAD

**Issue by estercheyn** [cenfun/vitest-monocart-coverage#6]
Hello, 

I tried to setup the vitest-monocart-coverage reporter with the following configs: 

mcr.config.js

```
export default {
    provider: 'v8',
    logging: 'info',
    name: 'My Vitest Coverage Report',

    reports: [
        'console-details',
        'v8'
    ],
    lcov: true,

    outputDir: './coverage',
    cacheDir: './coverage/.cache',
    inputDir: './coverage/.cache',
    onEnd: (results) => {
        console.log(`coverage report generated: ${results.reportPath}`);
    }
};

```

vitest.config

```
 ...
test: {
    include: ['src/**/*.test.?(c|m)[jt]s?(x)'],
    setupFiles: ['./src/setupTests.ts'],
    coverage: {
      include: ['src'],
      provider: 'custom',
      customProviderModule: 'vitest-monocart-coverage'
    }
    ...
```
    

 However, I receive the following error after the tests are run successfully, even though the `.json` files are generated in the cache folder: 
    `[MCR] Not found coverage data in dir(s): coverage/.cache, coverage/.cache`
    
  
    
 Is there anything wrong with the setup?

**Comment by cenfun** [comment]
there is no need to set `cacheDir` and `inputDir`, try remove them
```js
export default {
    provider: 'v8',
    logging: 'info',
    name: 'My Vitest Coverage Report',

    reports: [
        'console-details',
        'v8'
    ],
    lcov: true,

    outputDir: './coverage',

    onEnd: (results) => {
        console.log(`coverage report generated: ${results.reportPath}`);
    }
};

```

**Comment by estercheyn** [comment]
I also tried not setting them, but I still get the same error. I also tried not setting `outputDir` , but then I get the same error for the default directory.
I'm using `vitest-monocart-coverage: 2.1.1` and `vitest: 2.1.5`

**Comment by estercheyn** [comment]
It works now. I initially only ran one test suite and I noticed that the cache was generated only after it was tried to generate the report. When I ran multiple tests, it worked because the cache was generated while the tests were running.
